let car = 'subaru';
let bike = 'yamaha';
let fruit = 'apple';
let number = 42;
let gender = 'girl';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is bike == 'yamaha'? I predict True.");
console.log(bike == 'yamaha');
console.log("Is fruit == 'apple'? I predict True.");
console.log(fruit == 'apple');
console.log("Is number == 42? I predict True.");
console.log(number == 42);
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is bike != 'yamaha'? I predict False.");
console.log(bike != 'yamaha');
console.log("Is fruit == 'banana'? I predict False.");
console.log(fruit == 'banana');
console.log("Is number != 42? I predict False.");
console.log(number != 42);
console.log("Is gender == girl? I predict False.");
console.log(gender == 'boy');
export {};
